// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PC_ConsoleGames.Infrastructure.Data;

#nullable disable

namespace PC_ConsoleGames.Infrastructure.Migrations
{
    [DbContext(typeof(GameDBContext))]
    [Migration("20230924182841_new_project")]
    partial class new_project
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PC_ConsoleGames.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PC_ConsoleGames.Core.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and ceaseless body modification.\r\n",
                            Developer = "CD Projekt RED",
                            Name = "Cyberpunk 2077",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg?t=1695308476",
                            Publisher = "CD Projekt RED",
                            Rating = 80.0,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: 64-bit Windows 10\r\nProcessor: Core i7-6700 or Ryzen 5 1600\r\nMemory: 12 GB RAM\r\nGraphics: GeForce GTX 1060 6GB or Radeon RX 580 8GB or Arc A380\r\nDirectX: Version 12\r\nStorage: 70 GB available space\r\nAdditional Notes: SSD required. Attention: In this game you will encounter a variety of visual effects that may provide seizures or loss of consciousness in a minority of people. If you or someone you know experiences any of the above symptoms while playing, stop and seek medical attention immediately.\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: 64-bit Windows 10\r\nProcessor: Core i7-12700 or Ryzen 7 7800X3D\r\nMemory: 16 GB RAM\r\nGraphics: GeForce RTX 2060 SUPER or Radeon RX 5700 XT or Arc A770\r\nDirectX: Version 12\r\nStorage: 70 GB available space\r\nAdditional Notes: SSD required.\r\n"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Discover a reborn Mortal Kombat™ Universe created by the Fire God Liu Kang. Mortal Kombat™ 1 ushers in a new era of the iconic franchise with a new fighting system, game modes, and fatalities!\r\n",
                            Developer = "NetherRealm Studios, QLOC",
                            Name = "Mortal Kombat 1",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/1971870/header.jpg?t=1695256145",
                            Publisher = "Warner Bros. Games",
                            Rating = 76.0,
                            ReleaseDate = new DateTime(2023, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 64-bit\r\nProcessor: Intel® Core™ i5-6600 | AMD Ryzen™ 3 3100 or Ryzen™ 5 2600\r\nMemory: 8 GB RAM\r\nGraphics: Nvidia GeForce® GTX 980 or AMD Radeon™ RX 470 or Intel® Arc™ A750\r\nDirectX: Version 12\r\nStorage: 100 GB available space\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10/11 64-bit\r\nProcessor: Intel® Core™ i5-8400 | AMD Ryzen™ 5 3600X\r\nMemory: 8 GB RAM\r\nGraphics: Nvidia GeForce® GTX 1080 Ti or AMD Radeon™ RX 5700 XT or Intel® Arc™ A770\r\nDirectX: Version 12\r\nStorage: 100 GB available space\r\n"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Starfield is the first new universe in 25 years from Bethesda Game Studios, the award-winning creators of The Elder Scrolls V: Skyrim and Fallout 4.\r\n",
                            Developer = "Bethesda Game Studios",
                            Name = "Starfield",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/header.jpg?t=1694716152",
                            Publisher = "Bethesda Softworks",
                            Rating = 75.0,
                            ReleaseDate = new DateTime(2023, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nOS: Windows 10 version 21H1 (10.0.19043)\r\nProcessor: AMD Ryzen 5 2600X, Intel Core i7-6800K\r\nMemory: 16 GB RAM\r\nGraphics: AMD Radeon RX 5700, NVIDIA GeForce 1070 Ti\r\nDirectX: Version 12\r\nStorage: 125 GB available space\r\nAdditional Notes: SSD Required\r\nRECOMMENDED:\r\nOS: Windows 10/11 with updates\r\nProcessor: AMD Ryzen 5 3600X, Intel i5-10600K\r\nMemory: 16 GB RAM\r\nGraphics: AMD Radeon RX 6800 XT, NVIDIA GeForce RTX 2080\r\nDirectX: Version 12\r\nNetwork: Broadband Internet connection\r\nStorage: 125 GB available space\r\nAdditional Notes: SSD Required\r\n"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Baldur’s Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons & Dragons, where your choices shape a tale of fellowship and betrayal, survival and sacrifice, and the lure of absolute power.\r\n",
                            Developer = "Larian Studios",
                            Name = "Baldur`s Gate 3",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg?t=1695393586",
                            Publisher = "Larian Studios",
                            Rating = 96.0,
                            ReleaseDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 64-bit\r\nProcessor: Intel I5 4690 / AMD FX 8350\r\nMemory: 8 GB RAM\r\nGraphics: Nvidia GTX 970 / RX 480 (4GB+ of VRAM)\r\nDirectX: Version 11\r\nStorage: 150 GB available space\r\nAdditional Notes: SSD required\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 64-bit\r\nProcessor: Intel i7 8700K / AMD r5 3600\r\nMemory: 16 GB RAM\r\nGraphics: Nvidia 2060 Super / RX 5700 XT (8GB+ of VRAM)\r\nDirectX: Version 11\r\nStorage: 150 GB available space\r\nAdditional Notes: SSD required\r\n"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Survival is just the beginning. Six years have passed since the biological disaster in Raccoon City. Leon S. Kennedy, one of the survivors, tracks the president's kidnapped daughter to a secluded European village, where there is something terribly wrong with the locals.\r\n",
                            Developer = "CAPCOM Co., Ltd.",
                            Name = "Resident Evil 4",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header_alt_assets_0.jpg?t=1695311474",
                            Publisher = "CAPCOM Co., Ltd.",
                            Rating = 97.0,
                            ReleaseDate = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 (64 bit)\r\nProcessor: AMD Ryzen 3 1200 / Intel Core i5-7500\r\nMemory: 8 GB RAM\r\nGraphics: AMD Radeon RX 560 with 4GB VRAM / NVIDIA GeForce GTX 1050 Ti with 4GB VRAM\r\nDirectX: Version 12\r\nNetwork: Broadband Internet connection\r\nAdditional Notes: Estimated performance (when set to Prioritize Performance): 1080p/45fps. ・Framerate might drop in graphics-intensive scenes. ・AMD Radeon RX 6700 XT or NVIDIA GeForce RTX 2060 required to support ray tracing.\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 (64 bit)/Windows 11 (64 bit)\r\nProcessor: AMD Ryzen 5 3600 / Intel Core i7 8700\r\nMemory: 16 GB RAM\r\nGraphics: AMD Radeon RX 5700 / NVIDIA GeForce GTX 1070\r\nDirectX: Version 12\r\nNetwork: Broadband Internet connection\r\nAdditional Notes: Estimated performance: 1080p/60fps ・Framerate might drop in graphics-intensive scenes. ・AMD Radeon RX 6700 XT or NVIDIA GeForce RTX 2070 required to support ray tracing.\r\n"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lies of P is a thrilling soulslike that takes the story of Pinocchio, turns it on its head, and sets it against the darkly elegant backdrop of the Belle Epoque era.\r\n",
                            Developer = "NEOWIZ",
                            Name = "Lies of P",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/1627720/header.jpg?t=1695272170",
                            Publisher = "NEOWIZ",
                            Rating = 86.0,
                            ReleaseDate = new DateTime(2023, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 64bit\r\nProcessor: AMD Ryzen 3 1200／Intel Core i3-6300\r\nMemory: 8 GB RAM\r\nGraphics: AMD Radeon RX 560 4GB / NVIDIA GeForce GTX 960 4GB\r\nDirectX: Version 12\r\nStorage: 50 GB available space\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 64bit\r\nProcessor: AMD Ryzen 3 1200／Intel Core i3-6300\r\nMemory: 16 GB RAM\r\nGraphics: AMD Radeon RX 6500 XT 4GB / NVIDIA GeForce GTX 1660 6GB\r\nDirectX: Version 12\r\nStorage: 50 GB available space\r\n"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Raise a city from the ground up and transform it into a thriving metropolis with the most realistic city builder ever. Push your creativity and problem-solving to build on a scale you've never experienced. With deep simulation and a living economy, this is world-building without limits.",
                            Developer = "Colossal Order Ltd.",
                            Name = "Cities: Skylines II",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/949230/header.jpg?t=1695281898",
                            Publisher = "Paradox Interactive",
                            Rating = 0.0,
                            ReleaseDate = new DateTime(2023, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows® 10 Home 64 Bit\r\nProcessor: Intel® Core™ i7-4790K / AMD® Ryzen™ 5 1600X\r\nMemory: 8 GB RAM\r\nGraphics: Nvidia® GeForce™ GTX 780 (3GB) or AMD® Radeon™ RX 470 (4GB)\r\nSound Card: TBC\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows® 10 Home 64 Bit | Windows® 11\r\nProcessor: Intel® Core™ i7-9700K | AMD® Ryzen™ 5 5600X\r\nMemory: 16 GB RAM\r\nGraphics: Nvidia® GeForce™ RTX 2080 Ti (11GB) | AMD® Radeon™ RX 6800 XT (16GB)\r\nSound Card: TBC"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Your Ultimate Horizon Adventure awaits! Explore the vibrant open world landscapes of Mexico with limitless, fun driving action in the world’s greatest cars. Conquer the rugged Sierra Nueva in the ultimate Horizon Rally experience. Requires Forza Horizon 5 game, expansion sold separately.",
                            Developer = "Playground Games",
                            Name = "Forza Horizon 5",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg?t=1694801571",
                            Publisher = "Xbox Game Studios",
                            Rating = 88.0,
                            ReleaseDate = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 version 15063.0 or higher\r\nProcessor: Intel i5-4460 or AMD Ryzen 3 1200\r\nMemory: 8 GB RAM\r\nGraphics: NVidia GTX 970 OR AMD RX 470\r\nDirectX: Version 12\r\nNetwork: Broadband Internet connection\r\nStorage: 110 GB available space\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 version 15063.0 or higher\r\nProcessor: Intel i5-8400 or AMD Ryzen 5 1500X\r\nMemory: 16 GB RAM\r\nGraphics: NVidia GTX 1070 OR AMD RX 590\r\nDirectX: Version 12\r\nNetwork: Broadband Internet connection\r\nStorage: 110 GB available space\r\n"
                        },
                        new
                        {
                            Id = 9,
                            Description = "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.\r\n",
                            Developer = "FromSoftware Inc.",
                            Name = "Elden Ring",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg?t=1683618443",
                            Publisher = "FromSoftware Inc., Bandai Namco Entertainment",
                            Rating = 92.0,
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10\r\nProcessor: INTEL CORE I5-8400 or AMD RYZEN 3 3300X\r\nMemory: 12 GB RAM\r\nGraphics: NVIDIA GEFORCE GTX 1060 3 GB or AMD RADEON RX 580 4 GB\r\nDirectX: Version 12\r\nStorage: 60 GB available space\r\nSound Card: Windows Compatible Audio Device\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10/11\r\nProcessor: INTEL CORE I7-8700K or AMD RYZEN 5 3600X\r\nMemory: 16 GB RAM\r\nGraphics: NVIDIA GEFORCE GTX 1070 8 GB or AMD RADEON RX VEGA 56 8 GB\r\nDirectX: Version 12\r\nStorage: 60 GB available space\r\nSound Card: Windows Compatible Audio Device\r\n"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The Mass Effect™ Legendary Edition includes single-player base content and over 40 DLC from the highly acclaimed Mass Effect, Mass Effect 2, and Mass Effect 3 games, including promo weapons, armors, and packs — remastered and optimized for 4K Ultra HD.\r\n",
                            Developer = "BioWare",
                            Name = "Mass Effect™ Legendary Edition",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/1328670/header.jpg?t=1669773470",
                            Publisher = "Electronic Arts",
                            Rating = 83.0,
                            ReleaseDate = new DateTime(2021, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: 64-bit Windows 10\r\nProcessor: Intel Core i5 3570 or AMD FX-8350\r\nMemory: 8 GB RAM\r\nGraphics: GPU: NVIDIA GTX 760, AMD Radeon 7970 / R9280X GPU RAM: 2 GB Video Memory\r\nDirectX: Version 11\r\nStorage: 120 GB available space\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: 64-bit Windows 10\r\nProcessor: Intel Core i7-7700 or AMD Ryzen 7 3700X\r\nMemory: 16 GB RAM\r\nGraphics: GPU: NVIDIA GTX 1070 / RTX 200, Radeon Vega 56, GPU RAM: 4 GB Video Memory\r\nDirectX: Version 11\r\nStorage: 120 GB available space\r\n"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Hogwarts Legacy is an immersive, open-world action RPG. Now you can take control of the action and be at the center of your own adventure in the wizarding world.\r\n",
                            Developer = "Avalanche Software",
                            Name = "Hogwarts Legacy",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/990080/header.jpg?t=1694060626",
                            Publisher = "Warner Bros. Games",
                            Rating = 92.0,
                            ReleaseDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: 64-bit Windows 10\r\nProcessor: Intel Core i5-6600 (3.3Ghz) or AMD Ryzen 5 1400 (3.2Ghz)\r\nMemory: 16 GB RAM\r\nGraphics: NVIDIA GeForce GTX 960 4GB or AMD Radeon RX 470 4GB\r\nDirectX: Version 12\r\nStorage: 85 GB available space\r\nAdditional Notes: SSD (Preferred), HDD (Supported), 720p/30 fps, Low Quality Settings\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: 64-bit Windows 10\r\nProcessor: Intel Core i7-8700 (3.2Ghz) or AMD Ryzen 5 3600 (3.6 Ghz)\r\nMemory: 16 GB RAM\r\nGraphics: NVIDIA GeForce 1080 Ti or AMD Radeon RX 5700 XT or INTEL Arc A770\r\nDirectX: Version 12\r\nStorage: 85 GB available space\r\nAdditional Notes: SSD, 1080p/60 fps, High Quality Settings\r\n"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Love, fight, scheme, and claim greatness. Determine your noble house’s legacy in the sprawling grand strategy of Crusader Kings III. Death is only the beginning as you guide your dynasty’s bloodline in the rich and larger-than-life simulation of the Middle Ages.",
                            Developer = "Paradox Development Studio",
                            Name = "Crusader Kings III",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/1158310/header.jpg?t=1692714098",
                            Publisher = "Paradox Interactive",
                            Rating = 92.0,
                            ReleaseDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows® 8.1 64 bit / Windows® 10 Home 64 bit\r\nProcessor: Intel® Core™ i3-2120 / AMD® FX 6350\r\nMemory: 6 GB RAM\r\nGraphics: Nvidia® GeForce™ GTX 660 (2GB) / AMD® Radeon™ HD 7870 (2GB) / Intel® Iris Pro™ 580 / Intel® Iris® Plus G7 / AMD® Radeon™ Vega 11\r\nStorage: 8 GB available space\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows® 10 Home 64 bit\r\nProcessor: Intel® Core™ i5-4670K / AMD® Ryzen™ 5 2400G\r\nMemory: 8 GB RAM\r\nGraphics: Nvidia® GeForce™ GTX 1650 (4GB) / AMD® Radeon™ R9 390X (8GB)\r\nStorage: 8 GB available space\r\n"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, RDR2 is the epic tale of outlaw Arthur Morgan and the infamous Van der Linde gang, on the run across America at the dawn of the modern age. Also includes access to the shared living world of Red Dead Online.\r\n",
                            Developer = "Rockstar Games",
                            Name = "Red Dead Redemption 2",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg?t=1695140956",
                            Publisher = "Rockstar Games",
                            Rating = 90.0,
                            ReleaseDate = new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 - April 2018 Update (v1803)\r\nProcessor: Intel® Core™ i7-4770K / AMD Ryzen 5 1500X\r\nMemory: 12 GB RAM\r\nGraphics: Nvidia GeForce GTX 1060 6GB / AMD Radeon RX 480 4GB\r\nNetwork: Broadband Internet connection\r\nStorage: 150 GB available space\r\nSound Card: Direct X Compatible\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 - April 2018 Update (v1803)\r\nProcessor: Intel® Core™ i7-4770K / AMD Ryzen 5 1500X\r\nMemory: 12 GB RAM\r\nGraphics: Nvidia GeForce GTX 1060 6GB / AMD Radeon RX 480 4GB\r\nNetwork: Broadband Internet connection\r\nStorage: 150 GB available space\r\nSound Card: Direct X Compatible\r\n"
                        },
                        new
                        {
                            Id = 14,
                            Description = "An inadvertent brush with the mob thrusts cabdriver Tommy Angelo into the world of organized crime. Initially uneasy about falling in with the Salieri family, the rewards become too big to ignore.\r\n",
                            Developer = "Hangar 13",
                            Name = "Mafia: Definitive Edition",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/1030840/header.jpg?t=1632420251",
                            Publisher = "2K",
                            Rating = 86.0,
                            ReleaseDate = new DateTime(2020, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 64-bit\r\nProcessor: Intel Core-i5 2550K 3.4GHz / AMD FX 8120 3.1 GHz\r\nMemory: 6 GB RAM\r\nGraphics: NVIDIA GeForce GTX 660 / AMD Radeon HD 7870\r\nDirectX: Version 11\r\nStorage: 50 GB available space\r\nSound Card: DirectX Compatible\r\nRECOMMENDED:\r\nRequires a 64-bit processor and operating system\r\nOS: Windows 10 64-bit\r\nProcessor: Intel Core-i7 3770 3.4GHz / AMD FX-8350 4.2GHz\r\nMemory: 16 GB RAM\r\nGraphics: NVIDIA GeForce GTX 1080 / AMD Radeon RX 5700\r\nDirectX: Version 11\r\nStorage: 50 GB available space\r\nSound Card: DirectX Compatible\r\n"
                        },
                        new
                        {
                            Id = 15,
                            Description = "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy, a living weapon that can alter the shape of the world.\r\n",
                            Developer = "Hangar 13",
                            Name = "The Witcher® 3: Wild Hunt",
                            Poster = "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg?t=1693590732",
                            Publisher = "2K",
                            Rating = 96.0,
                            ReleaseDate = new DateTime(2015, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemRequirements = "MINIMUM:\r\nOS: 64-bit Windows 7, 64-bit Windows 8 (8.1)\r\nProcessor: Intel CPU Core i5-2500K 3.3GHz / AMD A10-5800K APU (3.8GHz)\r\nMemory: 6 GB RAM\r\nGraphics: Nvidia GPU GeForce GTX 660 / AMD GPU Radeon HD 7870\r\nDirectX: Version 11\r\nStorage: 50 GB available space\r\nRECOMMENDED:\r\nOS: 64-bit Windows 10/11\r\nProcessor: Intel Core i5-7400 / Ryzen 5 1600\r\nMemory: 8 GB RAM\r\nGraphics: Nvidia GTX 1070 / Radeon RX 480\r\nDirectX: Version 12\r\nStorage: 50 GB available space\r\n"
                        });
                });

            modelBuilder.Entity("PC_ConsoleGames.Core.Entities.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GamesGenres");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 6
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 6,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 6,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 7,
                            GenreId = 5
                        },
                        new
                        {
                            GameId = 8,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 8,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 8,
                            GenreId = 7
                        },
                        new
                        {
                            GameId = 8,
                            GenreId = 8
                        },
                        new
                        {
                            GameId = 8,
                            GenreId = 5
                        },
                        new
                        {
                            GameId = 9,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 9,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 10,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 10,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 11,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 11,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 11,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 12,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 12,
                            GenreId = 5
                        },
                        new
                        {
                            GameId = 12,
                            GenreId = 6
                        },
                        new
                        {
                            GameId = 13,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 13,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 14,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 14,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 15,
                            GenreId = 1
                        });
                });

            modelBuilder.Entity("PC_ConsoleGames.Core.Entities.GameLanguage", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("GamesLanguages");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 2
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 7
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 13
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 14
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 15
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 16
                        },
                        new
                        {
                            GameId = 1,
                            LanguageId = 17
                        },
                        new
                        {
                            GameId = 2,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 2,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 2,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 2,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 2,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 2,
                            LanguageId = 7
                        },
                        new
                        {
                            GameId = 2,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 2,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 2,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 2,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 2,
                            LanguageId = 14
                        },
                        new
                        {
                            GameId = 3,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 3,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 3,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 3,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 3,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 3,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 3,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 3,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 3,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 3,
                            LanguageId = 14
                        },
                        new
                        {
                            GameId = 4,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 4,
                            LanguageId = 2
                        },
                        new
                        {
                            GameId = 4,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 4,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 4,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 4,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 4,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 4,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 4,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 4,
                            LanguageId = 17
                        },
                        new
                        {
                            GameId = 5,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 5,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 5,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 5,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 5,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 5,
                            LanguageId = 7
                        },
                        new
                        {
                            GameId = 5,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 5,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 5,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 5,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 5,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 6,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 6,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 6,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 6,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 6,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 6,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 6,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 6,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 6,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 6,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 6,
                            LanguageId = 14
                        },
                        new
                        {
                            GameId = 7,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 7,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 7,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 7,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 7,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 7,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 7,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 7,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 7,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 7,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 7,
                            LanguageId = 14
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 13
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 14
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 15
                        },
                        new
                        {
                            GameId = 8,
                            LanguageId = 17
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 14
                        },
                        new
                        {
                            GameId = 9,
                            LanguageId = 16
                        },
                        new
                        {
                            GameId = 10,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 10,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 10,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 10,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 10,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 10,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 10,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 10,
                            LanguageId = 14
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 7
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 11,
                            LanguageId = 14
                        },
                        new
                        {
                            GameId = 12,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 12,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 12,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 12,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 12,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 12,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 12,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 13,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 13,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 13,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 13,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 13,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 13,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 13,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 13,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 13,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 13
                        },
                        new
                        {
                            GameId = 14,
                            LanguageId = 14
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 1
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 3
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 4
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 5
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 6
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 7
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 8
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 9
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 10
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 11
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 12
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 13
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 14
                        },
                        new
                        {
                            GameId = 15,
                            LanguageId = 17
                        });
                });

            modelBuilder.Entity("PC_ConsoleGames.Core.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Indie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("PC_ConsoleGames.Core.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ukrainian"
                        },
                        new
                        {
                            Id = 3,
                            Name = "French"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Italian"
                        },
                        new
                        {
                            Id = 5,
                            Name = "German"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Korean"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Czech"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Polish"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Hungarian"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Thai"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Dutch"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PC_ConsoleGames.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PC_ConsoleGames.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PC_ConsoleGames.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PC_ConsoleGames.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PC_ConsoleGames.Core.Entities.GameGenre", b =>
                {
                    b.HasOne("PC_ConsoleGames.Core.Entities.Game", "_Game")
                        .WithMany("Genres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PC_ConsoleGames.Core.Entities.Genre", "_Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Game");

                    b.Navigation("_Genre");
                });

            modelBuilder.Entity("PC_ConsoleGames.Core.Entities.GameLanguage", b =>
                {
                    b.HasOne("PC_ConsoleGames.Core.Entities.Game", "_Game")
                        .WithMany("Languages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PC_ConsoleGames.Core.Entities.Language", "_Language")
                        .WithMany("Games")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Game");

                    b.Navigation("_Language");
                });

            modelBuilder.Entity("PC_ConsoleGames.Core.Entities.Game", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("PC_ConsoleGames.Core.Entities.Genre", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("PC_ConsoleGames.Core.Entities.Language", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
